export const shoes = [
    {
        id: 1,
        nombre:"Zapatillas Nike Force 1 Le",
        precio:31.499,
        img:"img/js_img/Zapatillas Nike Force 1 Le.jpg",
        genero:"Niño",
        material:"Cuero sintético",
        garantia:"Contra defecto de fabricacion",
        paisFabricante:"NA",
        marca: "Nike",
        origen: "Importado",
    },
    {
        id:2,
        nombre:"Zapatillas Air Jordan 1 Mid SE",
        precio:69.999,
        img:"img/js_img/Zapatillas Nike Force 1 Le.jpg",
        genero:"Mujer",
        material:"Sintético",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"Nike",
        origen:"Importado",
    },
    {
        id:3,
        nombre:"Zapatillas Jordan 1 Low SE",
        precio:57.999,
        img:"img/js_img/Zapatillas Jordan 1 Low SE.jpg",
        genero:"Mujer",
        material:"Sintético",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"Nike",
        origen:"Importado",
    },
    {
        id:4,
        nombre:"Zapatillas Nike Court Vision Low",
        precio:39.999,
        img:"img/js_img/Zapatillas Nike Court Vision Low.jpg",
        genero:"Hombre",
        material:"Sintético",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"Nike",
        origen:"Importado",
    },
    {
        id:5,
        nombre:"Zapatillas Nike Dunk Low Se",
        precio:41.999,
        img:"img/js_img/Zapatillas Nike Dunk Low Se.jpg",
        genero:"Niños",
        material:"Mix de materiales Hi",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"Nike",
        origen:"Importado",
    },
    {
        id:6,
        nombre:"Zapatiilas Básquet Nike Air Jordan Legacy 312 Low",
        precio:71.999,
        img:"img/js_img/Zapatiilas Básquet Nike Air Jordan Legacy 312 Low.jpg",
        genero:"Hombre",
        material:"Mix de materiales Low",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"Nike",
        origen:"Importado",
    },
    {
        id:7,
        nombre:"Zapatillas Tenis Nike Court Legacy Lift",
        precio:49.999,
        img:"img/js_img/Zapatillas Tenis Nike Court Legacy Lift.jpg",
        genero:"Mujer",
        material:"Cuero y goma",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"Nike",
        origen:"Importado",
    },
    {
        id:8,
        nombre:"Zapatillas Nike Air Force 1 Mid React",
        precio:74.999,
        img:"img/js_img/Zapatillas Nike Air Force 1 Mid React.jpg",
        genero:"Hombre",
        material:"Sintético",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"Nike",
        origen:"Importado",
    },
    {
        id:9,
        nombre:"Zapatillas Nike Air Force 1 07 Se",
        precio:56.999,
        img:"img/js_img/Zapatillas Nike Air Force 1 07 Se.jpg",
        genero:"Mujer",
        material:"cuero sintético",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"Indonesia",
        marca:"Nike",
        origen:"Importado",
    },
    {
        id:10,
        nombre:"Zapatillas Nike Air Max 97 SE",
        precio:86.999,
        img:"img/js_img/Zapatillas Nike Air Max 97 SE.jpg",
        genero:"Hombre",
        material:"Mix de materiales Hi",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"Nike",
        origen:"Importado",
    },
    {
        id:11,
        nombre:"Zapatillas Urbanas Nike Air Huarache",
        precio:58.999,
        img:"img/js_img/Zapatillas Urbanas Nike Air Huarache.jpg",
        genero:"Mujer",
        material:"Mix de materiales Hi",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"Nike",
        origen:"Importado",
    },
    {
        id:12,
        nombre:"Zapatillas Nike Air Max Pre-Day Se",
        precio:61.999,
        img:"img/js_img/Zapatillas Nike Air Max Pre-Day Se.jpg",
        genero:"Mujer",
        material:"Textil",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"Vietnam",
        marca:"Nike",
        origen:"Importado",
    },
    {
        id:13,
        nombre:"Zapatillas Nike Air Vapormax 2021 Fk Nn",
        precio:79.999,
        img:"img/js_img/Zapatillas Nike Air Vapormax 2021 Fk Nn.jpg",
        genero:"Mujer",
        material:"Mesh",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"Vietnam",
        marca:"Nike",
        origen:"Importado",
    },
    {
        id:14,
        nombre:"Zapatillas Nike Crater Impact",
        precio:36.999,
        img:"img/js_img/Zapatillas Nike Crater Impact.jpg",
        genero:"Mujer",
        material:"Mix de materiales Hi",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"Vietnam",
        marca:"Nike",
        origen:"Importado",
    },
    {
        id:15,
        nombre:"Zapatillas Urbanas adidas Retropy Adisuper",
        precio:58.999,
        img:"img/js_img/Zapatillas Urbanas adidas Retropy Adisuper.jpg",
        genero:"Mujer",
        material:"Mix de materiales Hi",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"adidas",
        origen:"Importado",
    },
    {
        id:16,
        nombre:"Zapatillas adidas Forum Low",
        precio:41.799,
        img:"img/js_img/Zapatillas adidas Forum Low.jpg",
        genero:"Hombre",
        material:" Cuero sintético",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"Argentina",
        marca:"adidas",
        origen:"Nacional",
    },
    {
        id:17,
        nombre:"Zapatillas adidas Forum Bold",
        precio:55.999,
        img:"img/js_img/Zapatillas adidas Forum Bold.jpg",
        genero:"Mujer",
        material:"Mix de materiales Low",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"adidas",
        origen:"Importado",
    },
    {
        id:18,
        nombre:"Zapatillas Urbanas adidas Astir",
        precio:45.999,
        img:"img/js_img/Zapatillas Urbanas adidas Astir.jpg",
        genero:"Mujer",
        material:"Mix de materiales Hi",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"adidas",
        origen:"Importado",
    },
    {
        id:19,
        nombre:"Zapatillas adidas Nmd R1",
        precio:45.999,
        img:"img/js_img/Zapatillas adidas Nmd R1.jpg",
        genero:"Hombre",
        material:"Cuero Flor low",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"China",
        marca:"adidas",
        origen:"Importado",
    },
    {
        id:20,
        nombre:"Zapatillas adidas Superstar",
        precio:38.399,
        img:"img/js_img/Zapatillas adidas Superstar.jpg",
        genero:"Hombre",
        material:"Cuero Flor low",
        garantia:"Contra defecto de fabricacion",
        paisFabricante:"Indonesia",
        marca:"adidas",
        origen:"Importado",
    },
    {
        id:21,
        nombre:"Zapatillas Urbana adidas Nmd R1 V2",
        precio:44.999,
        img:"img/js_img/Zapatillas Urbana adidas Nmd R1 V2.jpg",
        genero:"Hombre",
        material:"Mesh",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"adidas",
        origen:"Importado",
    },
    {
        id:22,
        nombre:"Zapatillas adidas Forum Low Vegan",
        precio:55.999,
        img:"img/js_img/Zapatillas adidas Forum Low Vegan.jpg",
        genero:"Mujer",
        material:"Sintético",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"adidas",
        origen:"Importado",
    },
    
    {
        id:22,
        nombre:"Zapatillas Urbanas adidas Superstar",
        precio:48.999,
        img:"img/js_img/Zapatillas Urbanas adidas Superstar.jpg",
        genero:"Mujer",
        material:"Sintético",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"adidas",
        origen:"Importado",
    },
    
    {
        id:23,
        nombre:"Zapatillas adidas Niteball Ii",
        precio:41.799,
        img:"img/js_img/Zapatillas adidas Niteball Ii.jpg",
        genero:"Hombre",
        material:"Mix de materiales Hi",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"NA",
        marca:"adidas",
        origen:"Importado",
    },
    
    {
        id:24,
        nombre:"Zapatillas Puma Slipstream Sue",
        precio:43.699,
        img:"img/js_img/Zapatillas Puma Slipstream Sue.jpg",
        genero:"Hombre",
        material:"Sintético",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"Argentina",
        marca:"Puma",
        origen:"Nacional",
    },
    
    {
        id:25,
        nombre:"Zapatillas Puma Slipstream Tr",
        precio:43.699,
        img:"img/js_img/Zapatillas Puma Slipstream Tr.jpg",
        genero:"Unisex",
        material:"Sintético",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"Argentina",
        marca:"Puma",
        origen:"Nacional",
    },
    
    {
        id:26,
        nombre:"Zapatillas Puma Cali Dream",
        precio:35.999,
        img:"img/js_img/Zapatillas Puma Cali Dream.jpg",
        genero:"Mujer",
        material:"Cuero",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"Argentina",
        marca:"Puma",
        origen:"Nacional",
    },
    
    {
        id:27,
        nombre:"Zapatillas Puma Mayze Leather S",
        precio:37.999,
        img:"img/js_img/Zapatillas Puma Mayze Leather S.jpg",
        genero:"Mujer",
        material:"Cuero",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"Argentina",
        marca:"Puma",
        origen:"Nacional",
    },
    
    {
        id:28,
        nombre:"Zapatillas Puma Suede Classic Xxi",
        precio:32.699,
        img:"img/js_img/Zapatillas Puma Suede Classic Xxi.jpg",
        genero:"Hombre",
        material:"Sintético",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"Argentina",
        marca:"Puma",
        origen:"Nacional",
    },
    
    {
        id:29,
        nombre:"Zapatillas Puma Slipstream",
        precio:43.699,
        img:"img/js_img/Zapatillas Puma Slipstream.jpg",
        genero:"Mujer",
        material:"cuero sintético",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"Argentina",
        marca:"Puma",
        origen:"Nacional",
    },
    
    {
        id:30,
        nombre:"Zapatillas Puma Slipstream Lth",
        precio:19.099,
        img:"img/js_img/Zapatillas Puma Slipstream Lth.jpg",
        genero:"Unisex",
        material:"Sintético",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"China",
        marca:"Puma",
        origen:"Importado",
    },
    
    {
        id:31,
        nombre:"Zapatillas Urbanas Puma Slipstream Tr",
        precio:43.699,
        img:"img/js_img/Zapatillas Urbanas Puma Slipstream Tr.jpg",
        genero:"Unisex",
        material:"Capellada: Cuero sintético / Suela: Goma",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"Argentina",
        marca:"Puma",
        origen:"Nacional",
    },
    
    {
        id:32,
        nombre:"Zapatillas Puma Rider Fv Future Vin",
        precio:28.399,
        img:"img/js_img/Zapatillas Puma Rider Fv Future Vin.jpg",
        genero:"Unisex",
        material:"Mix de materiales Hi",
        garantia:"Contra defecto de fabricación",
        paisFabricante:"China",
        marca:"Puma",
        origen:"Importado",
    },
]